ARG ROS2_BASE_IMG
FROM ${ROS2_BASE_IMG}
ARG ROS2_WORKSPACE
ARG ROS_DISTRO
ARG TARGET_TRIPLE

RUN rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL C.UTF-8
RUN apt-get install -y \
    python3-colcon-common-extensions \
    python3-pip \
    python3-rosdep \
    symlinks

COPY ${ROS2_WORKSPACE}/src /opt/workspace/src

WORKDIR /opt/workspace
RUN rm -f /etc/ros/rosdep/sources.list.d/20-default.list && rosdep init
RUN rosdep update
SHELL ["/bin/bash", "-c"]
# Ensure /opt/ros/${ROS_DISTRO}/share exists to avoid rosdep errors
RUN mkdir -p /opt/ros/${ROS_DISTRO}/share && touch /opt/ros/${ROS_DISTRO}/setup.bash
# Ignoring some packages as in https://index.ros.org/doc/ros2/Installation/Crystal/Linux-Install-Binary/#installing-the-missing-dependencies
RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && rosdep install --from-paths src /opt/ros/${ROS_DISTRO}/share \
    --ignore-src \
    -v \
    --rosdistro ${ROS_DISTRO} -y \
    --skip-keys "osrf_testing_tools_cpp poco_vendor tinyxml_vendor tinyxml2_vendor urdfdom  \
        rmw_connext_cpp rosidl_typesupport_connext_c rosidl_typesupport_connext_cpp rti-connext-dds-5.3.1 \
        console_bridge \
        fastcdr \
        fastrtps \
        libopensplice67 \
        libopensplice69 \
        rti-connext-dds-5.3.1 \
        urdfdom_headers"

# To avoid linker issues when using a compiler with different GLIBC and GLIBCXX
# root_path/usr should be used as CMAKE_FIND_ROOT_PATH in the toolchain file
RUN mkdir -p /root_path/usr \
 && ln -s ../lib/${TARGET_TRIPLE} /root_path/lib \
 && ln -s ../../usr/lib/${TARGET_TRIPLE} /root_path/usr/lib \
 && cp -r /usr/lib/gcc/${TARGET_TRIPLE}/7/* /root_path/usr/lib

WORKDIR /
RUN symlinks -rc .
